'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { parseYarnLock, parsePnpmLock, parseBunLock, resolveLockfile, viaChain } = require('../src/lockfiles');

const byKey = ({ deps }) => Object.fromEntries(deps.map((d) => [d.name, d.version]));
const edgeObj = ({ edges }) => Object.fromEntries([...edges].map(([k, v]) => [k, [...v].sort()]));

test('yarn classic: scopes, multi-selector entries, npm: aliases; file/git skipped; edges', () => {
  const parsed = parseYarnLock([
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
    '# yarn lockfile v1',
    '',
    '"@scope/pkg@^1.0.0", "@scope/pkg@^1.1.0":',
    '  version "1.2.3"',
    '  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-1.2.3.tgz"',
    '  dependencies:',
    '    chalk "^5.0.0"',
    '    "@other/dep" "^2.0.0"',
    '',
    'chalk@^5.0.0:',
    '  version "5.3.0"',
    '',
    '"alias-name@npm:real-pkg@^2":',
    '  version "2.0.1"',
    '',
    '"local@file:../local":',
    '  version "0.0.1"',
    '',
    '"gitdep@git+https://github.com/u/r.git":',
    '  version "3.0.0"',
  ].join('\n'));
  assert.deepStrictEqual(byKey(parsed), { '@scope/pkg': '1.2.3', chalk: '5.3.0', 'real-pkg': '2.0.1' });
  assert.deepStrictEqual(edgeObj(parsed), { '@scope/pkg': ['@other/dep', 'chalk'] });
});

test('yarn berry: resolution-based, npm: protocol only; edges', () => {
  const parsed = parseYarnLock([
    '__metadata:',
    '  version: 8',
    '',
    '"chalk@npm:^5.0.0":',
    '  version: 5.3.0',
    '  resolution: "chalk@npm:5.3.0"',
    '',
    '"myws@workspace:.":',
    '  version: 0.0.0-use.local',
    '  resolution: "myws@workspace:."',
    '',
    '"lodash@patch:lodash@npm%3A4.17.21#patch":',
    '  version: 4.17.21',
    '  resolution: "lodash@patch:lodash@npm%3A4.17.21#patch::version=4.17.21"',
    '',
    '"@scope/x@npm:1.0.0":',
    '  version: 1.0.0',
    '  resolution: "@scope/x@npm:1.0.0"',
    '  dependencies:',
    '    chalk: "npm:^5.0.0"',
  ].join('\n'));
  assert.deepStrictEqual(byKey(parsed), { chalk: '5.3.0', '@scope/x': '1.0.0' });
  assert.deepStrictEqual(edgeObj(parsed), { '@scope/x': ['chalk'] });
});

test('pnpm v9: bare and quoted scoped keys; snapshots give edges', () => {
  const parsed = parsePnpmLock([
    "lockfileVersion: '9.0'",
    '',
    'importers:',
    '  .:',
    '    dependencies:',
    '      chalk:',
    '        specifier: ^5.0.0',
    '        version: 5.3.0',
    '',
    'packages:',
    '',
    '  chalk@5.3.0:',
    '    resolution: {integrity: sha512-xxx}',
    '',
    "  '@scope/x@1.0.0':",
    '    resolution: {integrity: sha512-yyy}',
    '',
    '  sharp@0.33.5:',
    '    resolution: {integrity: sha512-zzz}',
    '',
    'snapshots:',
    '',
    '  chalk@5.3.0: {}',
    '',
    '  sharp@0.33.5:',
    '    dependencies:',
    '      chalk: 5.3.0',
    "      '@scope/x': 1.0.0",
  ].join('\n'));
  assert.deepStrictEqual(byKey(parsed), { chalk: '5.3.0', '@scope/x': '1.0.0', sharp: '0.33.5' });
  assert.deepStrictEqual(edgeObj(parsed), { sharp: ['@scope/x', 'chalk'] });
});

test('pnpm v6: leading slash and peer parens', () => {
  const parsed = parsePnpmLock([
    "lockfileVersion: '6.0'",
    'packages:',
    '  /chalk@5.3.0:',
    '    resolution: {integrity: sha512-xxx}',
    '  /@scope/x@1.0.0(peer@2.0.0):',
    '    resolution: {integrity: sha512-yyy}',
    '    dependencies:',
    '      chalk: 5.3.0',
  ].join('\n'));
  assert.deepStrictEqual(byKey(parsed), { chalk: '5.3.0', '@scope/x': '1.0.0' });
  assert.deepStrictEqual(edgeObj(parsed), { '@scope/x': ['chalk'] });
});

test('pnpm v5: slash-separated versions and underscore peer suffixes', () => {
  const parsed = parsePnpmLock([
    'lockfileVersion: 5.4',
    'packages:',
    '  /chalk/5.3.0:',
    '    resolution: {integrity: sha512-xxx}',
    '  /@scope/x/1.0.0_peer@2.0.0:',
    '    resolution: {integrity: sha512-yyy}',
  ].join('\n'));
  assert.deepStrictEqual(byKey(parsed), { chalk: '5.3.0', '@scope/x': '1.0.0' });
});

test('bun.lock: JSONC tolerated, workspace entries skipped, edges from meta', () => {
  const parsed = parseBunLock([
    '// bun lockfile',
    '{',
    '  "lockfileVersion": 1,',
    '  "packages": {',
    '    "chalk": ["chalk@5.3.0", "", { "dependencies": { "ansi": "^1.0.0" } }, "sha512-xxx"],',
    '    "@scope/x": ["@scope/x@1.0.0"],',
    '    "myws": ["myws@workspace:packages/myws"],',
    '  },',
    '}',
  ].join('\n'));
  assert.deepStrictEqual(byKey(parsed), { chalk: '5.3.0', '@scope/x': '1.0.0' });
  assert.deepStrictEqual(edgeObj(parsed), { chalk: ['ansi'] });
});

test('viaChain walks reverse edges to a top-level package', () => {
  const edges = new Map([
    ['a', new Set(['b'])],
    ['b', new Set(['c'])],
    ['other', new Set(['b'])],
  ]);
  assert.deepStrictEqual(viaChain(edges, 'c'), ['a', 'b']);
  assert.deepStrictEqual(viaChain(edges, 'a'), []);
  // cycles do not hang
  const cyc = new Map([['x', new Set(['y'])], ['y', new Set(['x'])]]);
  assert.deepStrictEqual(viaChain(cyc, 'x'), ['y']);
});

test('resolveLockfile: type detection and directory search order', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'lens-lock-'));
  fs.writeFileSync(path.join(tmp, 'bun.lock'), '{"lockfileVersion":1,"packages":{}}');
  assert.strictEqual(resolveLockfile(tmp).type, 'bun');
  fs.writeFileSync(path.join(tmp, 'yarn.lock'), '# yarn lockfile v1\n');
  assert.strictEqual(resolveLockfile(tmp).type, 'yarn', 'yarn.lock outranks bun.lock');
  fs.writeFileSync(path.join(tmp, 'pnpm-lock.yaml'), "lockfileVersion: '9.0'\n");
  assert.strictEqual(resolveLockfile(tmp).type, 'yarn', 'yarn.lock outranks pnpm-lock.yaml');
  fs.writeFileSync(path.join(tmp, 'package-lock.json'), '{"lockfileVersion":3,"packages":{}}');
  assert.strictEqual(resolveLockfile(tmp).type, 'npm', 'package-lock.json outranks all');
  assert.strictEqual(resolveLockfile(path.join(tmp, 'pnpm-lock.yaml')).type, 'pnpm');
  assert.throws(() => resolveLockfile(path.join(tmp, 'nope')), /lockfile not found/);
  const only = fs.mkdtempSync(path.join(os.tmpdir(), 'lens-bunb-'));
  fs.writeFileSync(path.join(only, 'bun.lockb'), 'binary');
  assert.throws(() => resolveLockfile(only), /save-text-lockfile/);
});
