'use strict';
const { trustLabel } = require('./trust');

const RANK = { HIGH: 0, MEDIUM: 1, LOW: 2, SAFE: 3, ERROR: 4 };
const BADGE = { HIGH: '🔴 HIGH', MEDIUM: '🟠 MEDIUM', LOW: '🟡 LOW', SAFE: '🟢 SAFE', ERROR: '⚪ ERROR' };

// results: [{ name, version, rows: [{script, command, risk, signals}], error?,
//             via?, trust?, malicious?, advisories?, base?: {version, gained} }]
function packageRisk(r) {
  if (r.error) return 'ERROR';
  if (r.rows.length === 0) return 'SAFE';
  return r.rows.reduce((a, b) => (RANK[b.risk] < RANK[a] ? b.risk : a), 'SAFE');
}

const sortRank = (r) => (r.malicious ? -1 : RANK[packageRisk(r)]);
const esc = (s) => s.replace(/\|/g, '¦');

// Suggested npm v12 allowScripts block: version-pinned entries, true only for
// packages whose scripts showed no exec/network behavior. Humans flip the
// rest after review. Known-malicious packages are always false.
function buildAllowScripts(results) {
  const allow = {};
  for (const r of results) {
    if (r.rows.length === 0 && !r.error && !r.malicious) continue;
    allow[`${r.name}@${r.version}`] = r.malicious ? false : ['SAFE', 'LOW'].includes(packageRisk(r));
  }
  return { allowScripts: allow };
}

// The package cell carries identity plus context: how it got into the tree
// (via chain) and how much to trust the publisher (trust line).
function packageCell(r) {
  const parts = [`\`${r.name}@${r.version}\``];
  if (r.malicious) parts.push(`**⛔ ${esc(r.advisories.join(', '))}**`);
  if (r.via && r.via.length > 0) parts.push(`_via ${esc(r.via.join(' → '))}_`);
  const label = trustLabel(r.trust);
  if (label) parts.push(`_${esc(label)}_`);
  return parts.join('<br>');
}

function gainedNote(r) {
  if (!r.base) return null;
  if (r.base.gained === null) return `_upgrade from ${r.base.version}: base version could not be compared_`;
  return r.base.gained.length > 0
    ? `**⚠️ gained vs ${r.base.version}:** ${r.base.gained.map((s) => `\`${esc(s)}\``).join(' ')}`
    : `_no new capabilities vs ${r.base.version}_`;
}

function buildReport(results, { note } = {}) {
  const scripted = results.filter((r) => r.rows.length > 0 || r.error || r.malicious);
  const clean = results.length - scripted.length;
  const counts = { HIGH: 0, MEDIUM: 0, LOW: 0, SAFE: 0, ERROR: 0 };
  let malicious = 0;
  for (const r of scripted) {
    counts[packageRisk(r)]++;
    if (r.malicious) malicious++;
  }
  const lines = ['# npm-script-lens report', ''];
  lines.push(`Audited **${results.length}** locked packages: ` +
    (malicious ? `**${malicious}** ⛔ KNOWN MALICIOUS, ` : '') +
    `**${counts.HIGH}** HIGH, **${counts.MEDIUM}** MEDIUM, **${counts.LOW}** LOW risk install scripts; ` +
    `**${counts.SAFE + clean}** with no risky install-time behavior` +
    (counts.ERROR ? `; **${counts.ERROR}** could not be fetched` : '') + '.', '');
  if (note) lines.push(note, '');
  if (scripted.length > 0) {
    lines.push('| package | script | risk | signals |', '|---|---|---|---|');
    for (const r of [...scripted].sort((a, b) => sortRank(a) - sortRank(b))) {
      const badge = r.malicious ? '⛔ MALICIOUS' : BADGE[packageRisk(r)];
      if (r.error) {
        lines.push(`| ${packageCell(r)} | — | ${BADGE.ERROR} | ${r.error} |`);
        continue;
      }
      if (r.rows.length === 0) {
        lines.push(`| ${packageCell(r)} | — | ${badge} | flagged by OSV advisory |`);
        continue;
      }
      r.rows.forEach((row, i) => {
        const cell = [];
        if (row.signals.length > 0) cell.push(row.signals.map((s) => `\`${esc(s)}\``).join('<br>'));
        if (i === 0 && gainedNote(r)) cell.push(gainedNote(r));
        lines.push(`| ${packageCell(r)} | ${row.script} | ` +
          `${r.malicious ? badge : BADGE[row.risk]} | ${cell.join('<br>') || '—'} |`);
      });
    }
    lines.push('');
  }
  lines.push('## Suggested allowScripts', '',
    'Paste into your `package.json` (entries with risky behavior default to `false` — review, then flip the ones you trust):', '',
    '```json', JSON.stringify(buildAllowScripts(results), null, 2), '```', '',
    '_HIGH = spawns processes or runs constructed code · MEDIUM = network access · LOW = fs/env only · generated by npm-script-lens_');
  return lines.join('\n');
}

// SARIF 2.1.0 for GitHub code scanning: one result per risky package, level
// mapped from risk, anchored to the package's line in the lockfile so alerts
// annotate the right place.
const SARIF_RULES = {
  MALICIOUS: { id: 'known-malicious-package', text: 'Package is flagged as malicious by an OSV advisory' },
  HIGH: { id: 'high-risk-install-script', text: 'Install script can spawn processes or execute dynamically-built code' },
  MEDIUM: { id: 'network-install-script', text: 'Install script can reach the network' },
  LOW: { id: 'fs-env-install-script', text: 'Install script writes files or reads environment variables' },
  ERROR: { id: 'audit-error', text: 'Package could not be fetched from the registry for auditing' },
};
const SARIF_LEVEL = { MALICIOUS: 'error', HIGH: 'error', MEDIUM: 'warning', LOW: 'note', ERROR: 'note' };

function buildSarif(results, { lockPath = 'package-lock.json', lockText = '' } = {}) {
  const uri = lockPath.replace(/\\/g, '/');
  const lines = lockText.split(/\r?\n/);
  const lineOf = (name) => {
    const i = lines.findIndex((l) => l.includes(`node_modules/${name}"`) ||
      l.includes(`"${name}@`) || l.startsWith(`${name}@`) || l.includes(`/${name}@`) || l.includes(`/${name}/`));
    return i >= 0 ? i + 1 : 1;
  };
  const sarifResults = [];
  for (const r of results) {
    const risk = r.malicious ? 'MALICIOUS' : packageRisk(r);
    if (risk === 'SAFE') continue;
    const detail = r.malicious ? `Advisories: ${r.advisories.join(', ')}`
      : r.error ? r.error
        : r.rows.filter((row) => row.risk !== 'SAFE')
          .map((row) => `${row.script}: ${row.signals.join(' · ') || row.command}`).join(' | ');
    sarifResults.push({
      ruleId: SARIF_RULES[risk].id,
      level: SARIF_LEVEL[risk],
      message: { text: `${r.name}@${r.version} — ${SARIF_RULES[risk].text}. ${detail}` },
      locations: [{
        physicalLocation: {
          artifactLocation: { uri },
          region: { startLine: lineOf(r.name) },
        },
      }],
      partialFingerprints: { packageVersion: `${r.name}@${r.version}` },
    });
  }
  return {
    version: '2.1.0',
    $schema: 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
    runs: [{
      tool: {
        driver: {
          name: 'npm-script-lens',
          informationUri: 'https://github.com/Booyaka101/npm-script-lens',
          version: require('../package.json').version,
          rules: Object.values(SARIF_RULES).map((rule) => ({
            id: rule.id,
            shortDescription: { text: rule.text },
          })),
        },
      },
      results: sarifResults,
    }],
  };
}

// A stable, minimal, committable "receipt" of install-time behavior: sorted
// package keys -> { risk, capabilities } where capabilities are the signal
// KINDS (exec/net/fs/env/obf/bin), not the volatile human-readable strings.
// Deliberately excludes trust data (downloads, age, OSV) so the file changes
// only when a package's *behavior* changes — the git diff of this file IS the
// approval-surface change. Deterministic per tool version, so it round-trips
// through `manifest --check`.
function packageCapabilities(r) {
  const kinds = new Set();
  for (const row of r.rows) {
    for (const s of row.signals) {
      const kind = s.split(':')[0];
      if (kind !== 'ref') kinds.add(kind);
    }
  }
  return [...kinds].sort();
}

function buildManifest(results, { deep = false } = {}) {
  const packages = {};
  const errors = [];
  for (const r of results) {
    const key = `${r.name}@${r.version}`;
    if (r.error) { errors.push(key); continue; }
    const capabilities = packageCapabilities(r);
    if (capabilities.length === 0) continue; // no install-time behavior — omit
    packages[key] = { risk: packageRisk(r), capabilities };
  }
  const sorted = {};
  for (const key of Object.keys(packages).sort()) sorted[key] = packages[key];
  const manifest = { tool: 'npm-script-lens', version: require('../package.json').version };
  if (deep) manifest.deep = true;
  manifest.packages = sorted;
  return { manifest, errors };
}

const serializeManifest = (manifest) => `${JSON.stringify(manifest, null, 2)}\n`;

// Human-readable drift between a committed manifest and a freshly built one.
function diffManifests(oldM, newM) {
  const changes = [];
  if ((oldM.version || '?') !== newM.version) {
    changes.push(`tool ${oldM.version || '?'} → ${newM.version} — detector changed, re-review`);
  }
  if (Boolean(oldM.deep) !== Boolean(newM.deep)) {
    changes.push(`deep mode ${Boolean(oldM.deep)} → ${Boolean(newM.deep)}`);
  }
  const oldP = oldM.packages || {}, newP = newM.packages || {};
  const cap = (e) => (e && e.capabilities ? e.capabilities.join(' ') : '');
  for (const key of [...new Set([...Object.keys(oldP), ...Object.keys(newP)])].sort()) {
    if (!(key in oldP)) changes.push(`+ ${key}  ${newP[key].risk} [${cap(newP[key])}]`);
    else if (!(key in newP)) changes.push(`- ${key}  (no longer has install-time behavior)`);
    else if (JSON.stringify(oldP[key]) !== JSON.stringify(newP[key])) {
      changes.push(`~ ${key}  ${oldP[key].risk} [${cap(oldP[key])}] → ${newP[key].risk} [${cap(newP[key])}]`);
    }
  }
  return changes;
}

module.exports = {
  buildReport, buildAllowScripts, buildSarif, buildManifest, serializeManifest, diffManifests, packageRisk,
};
